import 'package:flutter/material.dart';


// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class AfterRegisterUserScreen extends StatelessWidget {
  const AfterRegisterUserScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Sukses(),
        ]),
      ),
    );
  }
}

class Sukses extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 412,
          height: 917,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 412,
                  height: 917,
                  padding: const EdgeInsets.all(24),
                  decoration: BoxDecoration(
                    gradient: LinearGradient(
                      begin: Alignment(0.50, -0.00),
                      end: Alignment(0.50, 1.00),
                      colors: [const Color(0xFF063CA8), const Color(0xFF2563EB)],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 25,
                top: 223,
                child: Container(
                  width: 364,
                  height: 557,
                  padding: const EdgeInsets.all(24),
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(24),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x19000000),
                        blurRadius: 10,
                        offset: Offset(0, 8),
                        spreadRadius: -6,
                      ),
                      BoxShadow(
                        color: Color(0x19000000),
                        blurRadius: 25,
                        offset: Offset(0, 20),
                        spreadRadius: -5,
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 25,
                top: 301,
                child: Container(
                  width: 360,
                  height: 378,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 120,
                        top: 95.15,
                        child: Container(
                          width: 120.92,
                          height: 20.15,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                        ),
                      ),
                      Positioned(
                        left: 148,
                        top: 167,
                        child: Text(
                          'Sukses',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFF1E1E1E),
                            fontSize: 20,
                            fontFamily: 'Open Sans',
                            fontWeight: FontWeight.w600,
                            height: 0.92,
                            letterSpacing: -0.46,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 205,
                        child: SizedBox(
                          width: 360,
                          child: Text(
                            'Selamat! Akun Anda telah '
                            'dibuat. \nKlik lanjutkan untuk masuk.',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: const Color(0xFF989898),
                              fontSize: 16,
                              fontFamily: 'Open Sans',
                              fontWeight: FontWeight.w400,
                              height: 1.50,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 132,
                        top: 19,
                        child: Container(
                          width: 95,
                          height: 95,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 10,
                        top: 239,
                        child: Container(
                          width: 340,
                          height: 50,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 100,
                                top: 14,
                                child: Text(
                                  'Perbaruiassword',
                                  style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 16,
                                    fontFamily: 'Open Sans',
                                    fontWeight: FontWeight.w700,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 21.99,
                        top: 289,
                        child: Container(
                          width: 316,
                          padding: const EdgeInsets.symmetric(vertical: 8),
                          decoration: ShapeDecoration(
                            color: const Color(0xFF18C07A),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(12),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              SizedBox(
                                width: 316,
                                child: Text(
                                  'Lanjutkan untuk masuk',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 15.75,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w700,
                                    height: 1.52,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 143,
                top: 33,
                child: Container(
                  width: 127,
                  height: 126,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/127x126"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 138,
                top: 159,
                child: SizedBox(
                  width: 136,
                  height: 61,
                  child: Text(
                    'KOTA \nSURABAYA',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'Ubuntu',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}